### ISSUE TITLE
objs to .ysce

### ISSUE THREAD

**Issue by home-gihub** [DDev247/ysce-tools#1]
Can we have an option to convert a directory of .obj to a .ysce?

**Comment by DDev247** [comment]
I could add it but you can also use the [blender addon (interchange_export_addon)](https://github.com/ange-yaghi/delta-studio/tree/master/tool-extensions/blender) and export it to .dia

**Comment by home-gihub** [comment]
i'm trying too mod steam engine simulator on steam (just so you know) but the plugin just outputs like 10 bytes an then stops.
Here what i'm doing:
- Export assets.ysce from steam engine sim
- open blender(4.x) and delete default objects
- Import .obj's to blender
- export to .dia
- compile dia to .ysce

**Comment by home-gihub** [comment]
UPDATE: When i select objects the plugin exports 1 object but stops and to 1 object that it exports is full of null bytes

**Comment by home-gihub** [comment]
UPDATE: i just needed 3.8 lts
